---

┏━━━┓┏━┓
┃┏━━┛┃┏┛
┃┗━━┳┛┗┳━━┳━┳━━┳━━┓
┃┏━━┻┓┏┫┏┓┃┏┫┏━┫┃━┫
┃┗━━┓┃┃┃┗┛┃┃┃┗━┫┃━┫
┗━━━┛┗┛┗━━┻┛┗━━┻━━┛

# if you want me to add more stuff please suggest it on my github.


# NOTE, this won't change the permission but it tells you what it is.

permission: "cfa.command"
...
